version: '3.8'

services:

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - 80:8000

  celery:
    build: .
    command: celery -A chat worker -l info

    links:
     - redis

