version: '3.8'

services:
  chat:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      redis_net:
      nginx_net:
    volumes:
      - .:/code
    restart: always
    ports:
      - 0.0.0.0:8001:8000

  celery:
    build: .
    command: celery -A chat worker -l info
    networks:
      redis_net:

networks:
  redis_net:
    name: redis_net
  nginx_net:
    name: nginx_net

